version: "3"

services:
  bookstack:
    image: linuxserver/bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=mariadb
      - DB_USER=bookstack
      - DB_PASS=yJryZaAfF3r3DEQv4VdJhABhDR6cNrY2
      - DB_DATABASE=bookstackapp
    volumes:
      - bookstack_data:/config
    networks:
      # - traefik-net
      - backend
    depends_on:
      - bookstack_db
    ports:
      - "10080:80"

  mariadb:
    image: linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=v9rp2BupDtNeDpJ9hAJ9n9mPZ7ewrPu7
      - TZ=Europe/Copenhagen
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - MYSQL_PASSWORD=yJryZaAfF3r3DEQv4VdJhABhDR6cNrY2
    volumes:
      - db_data:/config
    networks:
      - backend

volumes:
  db_data:
    driver: local

  bookstack_data:
    driver: local

networks:
  backend:
