# Docker Bookstack for swarm
# Default user and pass
# admin@admin.com
# password

version: "3.9"
services:
  bookstack:
    image: lscr.io/linuxserver/bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://XXX.XXX.XXX.XXX:6875
      - DB_HOST=maria_db
      - DB_PORT=3306
      - DB_USER=bookstack
      - FILE__DB_PASS=/run/secrets/bookstack_db_app_password
      - DB_DATABASE=bookstackapp
    secrets:
      - bookstack_db_app_password
    volumes:
      - app_data:/config
    ports:
      - 6875:80
    depends_on:
      - maria_db

  maria_db:
    image: lscr.io/linuxserver/mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/bookstack_db_root_password
      - TZ=Europe/Copenhagen
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=bookstack
      - FILE__MYSQL_PASSWORD=/run/secrets/bookstack_db_app_password

    secrets:
      - bookstack_db_root_password
      - bookstack_db_app_password

    volumes:
      - db_data:/config

secrets:
  bookstack_db_root_password:
    external: true
  bookstack_db_app_password:
    external: true

volumes:
  db_data:
    driver: local

  app_data:
    driver: local
