version: "3.8"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_admin_password
    secrets:
      - postgres_admin_password
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - 7080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@unknown.local
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    secrets:
      - pgadmin_password

    volumes:
      - pgdata:/var/lib/pgadmin

volumes:
  db_data:
    driver: local
  pgdata:
    driver: local

secrets:
  postgres_admin_password:
    external: true
  pgadmin_password:
    external: true
