version: '3.1'

services:
  mongo:
    image: mongo:4.2.1
    ports:
        - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: imh8nKU6aJitfC5CQUdoj3ua5MrpoDVmNYjcNWpCFh2dEQHg
    volumes:
        - mongodev_data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoexpress
      ME_CONFIG_MONGODB_ADMINPASSWORD: KA8mTahtAv9gxnomtrPH73qx9DdpFUnLLUmXtuD48BC87fbg

volumes:
  mongodev_data: